#!/usr/bin/env node
/**
 * Rebuild the static export that ../app publishes.
 *
 *   npm run build:export
 *
 * Why this script exists rather than a plain `next build`:
 *
 * 1. `output: "export"` supports only GET route handlers, and none that touch
 *    `Request` (see node_modules/next/dist/docs/01-app/02-guides/static-exports.md).
 *    src/app/api is ~246 handlers built on POST and Request, so the export
 *    cannot include it — the build fails outright. It is moved aside for the
 *    duration and put straight back, which is why the published export has no
 *    /api directory at all.
 *
 *    Losing the API is not a regression here: the published site has no server
 *    to run it. app/omni-shim.js patches window.fetch and answers the handful
 *    of endpoints the UI needs from the browser instead.
 *
 * 2. The restore has to survive a failed build. A crash between the move and
 *    the restore would leave the working tree without its API routes, and the
 *    next ordinary `next build` would quietly produce an app missing 246
 *    endpoints. Hence try/finally plus the same restore on SIGINT.
 *
 * The build goes to .next-export and is copied into ../app only after it
 * succeeds, so a failure never damages the site that is currently published.
 */
import { execFileSync } from "node:child_process";
import { existsSync, renameSync, rmSync, cpSync, readdirSync } from "node:fs";
import { join, dirname } from "node:path";
import { fileURLToPath } from "node:url";

const here = dirname(fileURLToPath(import.meta.url));
const root = join(here, "..");            // source/
const repo = join(root, "..");            // MadeEA OS/
const API = join(root, "src", "app", "api");
const API_PARKED = join(root, "src", "app", "_api.parked");
// With a custom distDir, `output: "export"` writes the finished site into that
// directory rather than the default ./out — and writes only the site, with none
// of the build artifacts (no cache, BUILD_ID, server/ or manifests), so it can
// be published as-is.
const OUT = join(root, ".next-export");
const APP = join(repo, "app");

function run(cmd, args, opts = {}) {
  execFileSync(cmd, args, { stdio: "inherit", cwd: root, ...opts });
}

let moved = false;
function restore() {
  if (moved && existsSync(API_PARKED)) {
    renameSync(API_PARKED, API);
    moved = false;
    console.log("[build-export] restored src/app/api");
  }
}
process.on("SIGINT", () => { restore(); process.exit(130); });

try {
  if (existsSync(API_PARKED)) {
    throw new Error(
      `${API_PARKED} already exists — a previous run was interrupted. ` +
      `Move it back to src/app/api by hand before rebuilding.`
    );
  }

  if (existsSync(API)) {
    renameSync(API, API_PARKED);
    moved = true;
    console.log("[build-export] parked src/app/api (export supports GET-only handlers)");
  }

  rmSync(OUT, { recursive: true, force: true });

  // tsconfig pulls in .next/types and .next/dev/types, which hold route
  // validators generated by the LAST build. Those reference src/app/api/**,
  // parked above, so the export's type check dies on generated files nobody
  // wrote — pointing at a path that does not exist during this build. They are
  // build output; the next server build regenerates them. The export writes its
  // own under .next-export, which tsconfig does not include.
  for (const stale of [join(root, ".next", "types"), join(root, ".next", "dev", "types")]) {
    rmSync(stale, { recursive: true, force: true });
  }

  console.log("[build-export] building…");
  // Call Next's bin with the current node rather than npx: since Node 20.12 /
  // 22, spawnSync refuses a .cmd shim without shell:true and fails with
  // EINVAL, and using a shell here would mean quoting a path that contains a
  // space ("For Work"). The bin is a plain .js file, so node runs it directly.
  run(process.execPath, [join(root, "node_modules", "next", "dist", "bin", "next"), "build", "--webpack"], {
    env: { ...process.env, MADEEA_EXPORT: "1", NODE_OPTIONS: "--max-old-space-size=3072" },
  });

  if (!existsSync(join(OUT, "index.html"))) {
    throw new Error("build finished but out/index.html is missing — refusing to publish it");
  }
} finally {
  restore();
}

// Only now is it safe to touch the published copy.
console.log("[build-export] replacing ../app");
for (const entry of readdirSync(APP)) {
  // .git lives at the repo root, not here, but be explicit anyway.
  if (entry === ".git") continue;
  rmSync(join(APP, entry), { recursive: true, force: true });
}
cpSync(OUT, APP, { recursive: true });

// Puts omni-shim.js in place and injects it as the first <script> of every
// page — it has to patch window.fetch before any Next bundle runs.
console.log("[build-export] injecting the shim");
run(process.execPath, [join(repo, "tools", "inject-shim.mjs"), APP, "/madeea-os/app"], { cwd: repo });

console.log("[build-export] done — commit ../app to publish");
